# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Joey Hyun
title: Computer Science Engineering, Games and Interactive Media
email: HyunJoey@msu.edu
# email_title: Email (Email title override)
phone: (858)-610-2530
# phone_title: Phone (Phone title override)
website:
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links

github_username:  joeyhyun1
instagram_username: joeyhyvn
linkedin_username: joey-hyun-32b237299

# Additional icon links
additional_links:

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/IMG_0709.JPG
about_content: | # this will include new lines to allow paragraphs
  Hello, I am currently a student at Michigan State University and making progress towards
    a bachelors in computer science engineering and games and interactive media.
    Below you can see more information about my qualifications and above are most
    of my social links.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Solar Car
          EGR 100 Solar Car Project
        description: | # this will include new lines to allow paragraphs
          With a team of four including me we designed a solar car that had to pass
          through multiple tests with materials that were given to us. 
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Sansu
        sub_title: Waiter/Host
        caption: March 2024 - Present
        quote: >
          Sansu is a Japanese Korean fusion resteraunt in East Lansing
        description: | # this will include new lines to allow paragraphs
          I am currently a server and host at Sansu.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Troy High School
        sub_title: High School Degree
        caption: 2019 - 2022
      - layout: top-right
        title: Michigan State University
        sub_title: BA Computer Science, BA Games and Interactive Media
        caption: 2022 - present
        
  - title: Skills
    layout: text
    content: |
      Microsoft Excel, Microsoft Word, Python, Unity, C#, Teamwork, Time Management, 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
